#!/usr/bin/env node
/**
 * Terminal Redux docs site builder.
 *
 * Scans docs/ for markdown and hand-written HTML documents, renders every .md
 * into a styled HTML page (sidebar + TOC + prev/next), and regenerates
 * docs/index.html. Output is committed and served straight from GitHub Pages
 * (source: main branch, /docs folder) — there is no build step on the server.
 *
 *   npm run docs
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { dirname, join, relative, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'docs');
const REPO = 'https://github.com/rentorious/terminal-redux';
const GENERATED = '<!-- generated by scripts/build-docs.mjs — edit the .md source, not this file -->';

/* Section headings on the index page and in the sidebar, keyed by folder.
   Unlisted folders fall back to a prettified folder name. */
const SECTIONS = {
  '.': { title: 'Overview', order: 0 },
  gameplan: { title: 'Gameplan', order: 1 },
};

const SITE = {
  name: 'Terminal Redux',
  title: 'Terminal Redux — Documentation',
  eyebrow: 'Terminal Redux',
  heading: 'Gameplan documents',
  sub: 'Everything written down so far: the market brief, the architecture spec, the build plan, the interview kit and the prototype scope. Markdown and interactive documents, all rendered.',
};

/* ------------------------------------------------------------------ utils */
const tidy = (html) => html.replace(/[ \t]+$/gm, '').replace(/\n{3,}/g, '\n\n');
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const stripTags = (s) => String(s).replace(/<[^>]+>/g, '');
const decode = (s) => String(s).replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'");

function slug(text) {
  return stripTags(decode(text)).toLowerCase().trim()
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'section';
}

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith('.') || entry === 'assets' || entry === 'node_modules') continue;
    const full = join(dir, entry);
    statSync(full).isDirectory() ? walk(full, out) : out.push(full);
  }
  return out;
}

/* --------------------------------------------------------------- markdown */
marked.setOptions({ gfm: true, breaks: false, mangle: false, headerIds: false });

/** Renders markdown, adds heading anchors, wraps tables, and returns the TOC. */
function renderMarkdown(md) {
  let html = marked.parse(md);
  const toc = [];
  const seen = new Map();

  html = html.replace(/<h([23])(?:\s[^>]*)?>([\s\S]*?)<\/h\1>/g, (_m, level, inner) => {
    let id = slug(inner);
    if (/^\d/.test(id)) id = `s-${id}`; // ids starting with a digit are awkward in CSS selectors
    if (seen.has(id)) { const n = seen.get(id) + 1; seen.set(id, n); id = `${id}-${n}`; } else seen.set(id, 1);
    toc.push({ level: Number(level), id, text: decode(stripTags(inner)).trim() });
    return `<h${level} id="${id}">${inner}<a class="anchor" href="#${id}" aria-label="Link to this section">#</a></h${level}>`;
  });

  // markdown task lists become checkboxes the reader can actually tick (state kept in localStorage)
  let task = 0;
  html = html.replace(/<li>(<input[^>]*type="checkbox"[^>]*>)/g, (_m, input) => {
    const checked = /checked/.test(input) ? ' checked' : '';
    return `<li class="task"><input type="checkbox" data-task="${task++}"${checked}>`;
  });

  html = html.replace(/<table>/g, '<div class="tblwrap"><table>').replace(/<\/table>/g, '</table></div>');
  // cross-links between documents point at the rendered page, not the raw markdown
  html = html.replace(/href="(?!https?:|\/\/|#)([^"]+)\.md(#[^"]*)?"/g, (_m, path, hash) => `href="${path}.html${hash || ''}"`);
  return { html, toc };
}

/** Pulls title, `**Key:** value` meta lines and a one-line summary out of a markdown doc. */
function parseMarkdown(raw) {
  const src = raw.replace(/^﻿/, '').replace(/\r\n/g, '\n');
  const lines = src.split('\n');

  let title = '';
  let i = 0;
  for (; i < lines.length; i++) {
    const m = /^#\s+(.+?)\s*$/.exec(lines[i]);
    if (m) { title = m[1].trim(); i++; break; }
    if (lines[i].trim()) break;
  }

  const meta = [];
  for (; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) { if (meta.length) break; else continue; }
    const m = /^\*\*(.+?):\*\*\s*(.+)$/.exec(line);
    if (!m) break;
    meta.push({ key: m[1].trim(), value: m[2].trim() });
  }

  let summary = '';
  for (; i < lines.length && !summary; i++) {
    const line = lines[i].trim();
    if (!line || line === '---' || line.startsWith('#') || line.startsWith('|') || line.startsWith('```')) continue;
    summary = line;
  }
  summary = plain(summary);
  if (summary.length > 230) summary = summary.slice(0, 227).replace(/\s+\S*$/, '') + '…';

  // strip the title + meta block; they are re-rendered by the page shell
  let body = src;
  if (title) {
    const idx = src.indexOf('\n', src.indexOf(`# ${title}`));
    body = src.slice(idx + 1);
  }
  body = body.replace(/^(?:\s*\*\*[^\n]+?:\*\*[^\n]*\n)+/, '').replace(/^\s*---\s*\n/, '').replace(/^\n+/, '');

  return { title, meta, summary, body };
}

/** Reads title / kind / summary out of a hand-written standalone HTML document. */
function parseStandaloneHtml(raw) {
  const title = decode((/<title>([\s\S]*?)<\/title>/i.exec(raw) || [, ''])[1]).trim();
  const eyebrow = decode(stripTags((/class="eyebrow"[^>]*>([\s\S]*?)<\/div>/i.exec(raw) || [, ''])[1])).trim();
  const sub = decode(stripTags((/class="sub"[^>]*>([\s\S]*?)<\/p>/i.exec(raw) || [, ''])[1])).replace(/\s+/g, ' ').trim();
  const kind = eyebrow.includes('·') ? eyebrow.split('·').pop().trim() : eyebrow;
  return { title, kind, summary: sub };
}

const shortTitle = (t) => t.replace(/^Terminal Redux\s*[—–-]\s*/, '').trim() || t;
/** Markdown inline -> plain text (no entities, no tags), for titles and summaries. */
const plain = (s) => decode(stripTags(marked.parseInline(String(s || '')))).replace(/\s+/g, ' ').trim();

/* ------------------------------------------------------------- collection */
const files = walk(DOCS).filter((f) => ['.md', '.html'].includes(extname(f).toLowerCase()));
const docs = [];

for (const file of files) {
  const rel = relative(DOCS, file).replace(/\\/g, '/');
  if (rel === 'index.html') continue;
  const ext = extname(file).toLowerCase();
  const raw = readFileSync(file, 'utf8');

  if (ext === '.html') {
    if (raw.includes(GENERATED)) continue; // our own output from a previous run
    const info = parseStandaloneHtml(raw);
    docs.push({
      kind: 'html', src: rel, url: rel, dir: dirname(rel),
      title: info.title || shortTitle(basename(rel, ext)),
      nav: shortTitle(info.title || basename(rel, ext)),
      summary: info.summary, label: info.kind || 'Interactive document', meta: [],
    });
  } else {
    const info = parseMarkdown(raw);
    docs.push({
      kind: 'md', src: rel, url: rel.replace(/\.md$/i, '.html'), dir: dirname(rel),
      title: info.title || basename(rel, ext),
      nav: shortTitle(info.title || basename(rel, ext)),
      summary: info.summary, label: 'Markdown', meta: info.meta, body: info.body,
    });
  }
}

const sectionOf = (dir) => SECTIONS[dir] || { title: dir.split('/').pop().replace(/[-_]/g, ' ').replace(/^\w/, (c) => c.toUpperCase()), order: 50 };

docs.sort((a, b) => {
  const sa = sectionOf(a.dir), sb = sectionOf(b.dir);
  if (sa.order !== sb.order) return sa.order - sb.order;
  if (a.dir !== b.dir) return a.dir.localeCompare(b.dir);
  if (a.kind !== b.kind) return a.kind === 'html' ? -1 : 1; // hand-built docs lead their section
  return a.src.localeCompare(b.src);
});

/* "**Version:** 0.2 · supersedes 02-build-plan-12-weeks.md" marks the older doc as superseded. */
const key = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, '');
for (const doc of docs) {
  const text = [doc.title, ...doc.meta.map((m) => `${m.key}: ${m.value}`)].join(' ');
  for (const m of text.matchAll(/supersedes\s+([\w.\-\/]+\.md)/gi)) {
    const target = docs.find((d) => key(basename(d.src)) === key(basename(m[1])));
    if (target && target !== doc) { target.superseded = true; target.supersededBy = doc; }
  }
}

const groups = [];
for (const doc of docs) {
  const title = sectionOf(doc.dir).title;
  let g = groups.find((x) => x.title === title);
  if (!g) groups.push((g = { title, docs: [] }));
  g.docs.push(doc);
}

/* ---------------------------------------------------------------- shell */
const upTo = (rel) => { const depth = rel.split('/').length - 1; return depth ? '../'.repeat(depth) : ''; };

const themeBoot = `<script>(function(){try{var t=localStorage.getItem('tr-theme');
if(!t)t=(window.matchMedia&&matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light';
document.documentElement.setAttribute('data-theme',t);}catch(e){}})();</script>`;

function head(title, base, description) {
  return `<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
${GENERATED}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
${description ? `<meta name="description" content="${esc(description)}">\n` : ''}${themeBoot}
<link rel="stylesheet" href="${base}assets/site.css">
</head>
<body>`;
}

function topbar(base, crumb) {
  return `<div class="topbar">
  <button class="btn" id="menuBtn" type="button">Docs</button>
  <a class="home" href="${base}index.html"><span class="mark"></span>${esc(SITE.name)}</a>
  ${crumb ? `<span class="crumb">/ ${esc(crumb)}</span>` : ''}
  <span class="spacer"></span>
  <button class="btn" id="themeToggle" type="button">Dark</button>
</div>`;
}

function sidebar(base, currentUrl) {
  const parts = [`<aside class="nav" aria-label="All documents">
<input id="navSearch" class="navsearch" type="search" placeholder="Filter documents  /" autocomplete="off">`];
  for (const g of groups) {
    parts.push(`<div class="group">${esc(g.title)}</div>`);
    for (const d of g.docs) {
      const current = d.url === currentUrl ? ' aria-current="page"' : '';
      const ext = d.kind === 'html' ? '<span class="ext">interactive</span>' : '';
      parts.push(`<a href="${base}${d.url}" data-title="${esc(d.nav)}"${current}>${esc(d.nav)}${ext}</a>`);
    }
  }
  parts.push('</aside>');
  return parts.join('\n');
}

function tocAside(toc) {
  if (toc.length < 3) return '';
  const items = toc.map((h) => `<a class="lvl${h.level}" href="#${h.id}">${esc(h.text)}</a>`).join('\n');
  return `<aside class="toc" aria-label="On this page"><div class="tlab">On this page</div>\n${items}\n</aside>`;
}

function pager(index, base) {
  const prev = docs[index - 1], next = docs[index + 1];
  if (!prev && !next) return '';
  const cell = (d, dir) => d
    ? `<a class="${dir}" href="${base}${d.url}"><div class="dir">${dir === 'prev' ? 'Previous' : 'Next'}</div><div class="ttl">${esc(d.nav)}</div></a>`
    : '<span></span>';
  return `<nav class="pager">${cell(prev, 'prev')}${cell(next, 'next')}</nav>`;
}

/* -------------------------------------------------------------- md pages */
let written = 0;
docs.forEach((doc, index) => {
  if (doc.kind !== 'md') return;
  const base = upTo(doc.url);
  const { html, toc } = renderMarkdown(doc.body);
  // short meta values become pills; long ones read better as lines under them
  const metaShort = doc.meta.filter((m) => plain(m.value).length <= 46);
  const metaLong = doc.meta.filter((m) => plain(m.value).length > 46);
  const metaPills = [
    metaShort.length ? `<div class="docmeta">${metaShort.map((m) => `<span class="pill"><b>${esc(m.key)}</b>${esc(plain(m.value))}</span>`).join('')}</div>` : '',
    metaLong.length ? `<div class="metalines">${metaLong.map((m) => `<div><b>${esc(m.key)}</b> ${esc(plain(m.value))}</div>`).join('')}</div>` : '',
  ].join('\n    ');
  const section = sectionOf(doc.dir).title;

  const page = `${head(doc.title, base, doc.summary)}
${topbar(base, doc.nav)}
<div class="shell${toc.length >= 3 ? ' with-toc' : ''}">
${sidebar(base, doc.url)}
<main>
  <article class="doc">
    <div class="eyebrow">${esc(SITE.name)} · ${esc(section)}</div>
    <h1>${esc(plain(shortTitle(doc.title)))}</h1>
    ${metaPills}
    ${doc.superseded ? `<div class="notice">Superseded by <a href="${base}${doc.supersededBy.url}">${esc(doc.supersededBy.nav)}</a>. Kept for reference.</div>` : ''}
${html}
  </article>
  ${pager(index, base)}
  <div class="docfoot">
    <a href="${base}index.html">← All documents</a>
    <span class="spacer"></span>
    <a href="${REPO}/blob/main/docs/${doc.src}">Edit source (${esc(basename(doc.src))})</a>
  </div>
</main>
${tocAside(toc)}
</div>
<script src="${base}assets/site.js"></script>
</body>
</html>
`;
  writeFileSync(join(DOCS, doc.url), tidy(page));
  written++;
});

/* ------------------------------------------------------------ index page */
const accents = ['', 'c2', 'c3'];
let accent = 0;
const cardsHtml = groups.map((g) => {
  const cards = g.docs.map((d) => {
    const cls = accents[accent++ % accents.length];
    const version = d.meta.find((m) => /^version$/i.test(m.key));
    const parts = version ? plain(version.value).split('·').map((s) => s.trim()) : [];
    const pills = (d.superseded ? ['Superseded'] : d.kind === 'html' ? ['Interactive'] : [])
      .concat(parts[0] ? [`v${parts[0].replace(/^v/i, '')}`] : [])
      .concat(parts[1] ? [parts[1]] : [])
      .filter(Boolean).slice(0, 3);
    return `  <a class="card ${cls}" href="${d.url}">
    <div class="rule"></div>
    <div class="lab">${esc(d.label)}</div>
    <h2>${esc(plain(shortTitle(d.title)))}</h2>
    <p>${esc(d.summary || '')}</p>
    <div class="meta">${pills.map((p) => `<span class="pill">${esc(p)}</span>`).join('')}</div>
    <div class="go">Open →</div>
  </a>`;
  }).join('\n');
  return `<div class="sectitle">${esc(g.title)}</div>\n<div class="cards">\n${cards}\n</div>`;
}).join('\n\n');

const indexPage = `${head(SITE.title, '', SITE.sub)}
${topbar('', '')}
<div class="home-wrap">
<header class="home-head">
  <div class="eyebrow">${esc(SITE.eyebrow)}</div>
  <h1>${esc(SITE.heading)}</h1>
  <p class="sub">${esc(SITE.sub)}</p>
</header>

${cardsHtml}

<footer class="home-foot">
  ${docs.length} documents · Source: <a href="${REPO}">github.com/rentorious/terminal-redux</a>
</footer>
</div>
<script src="assets/site.js"></script>
</body>
</html>
`;
writeFileSync(join(DOCS, 'index.html'), tidy(indexPage));

if (!existsSync(join(DOCS, '.nojekyll'))) writeFileSync(join(DOCS, '.nojekyll'), '');

console.log(`docs: ${written} markdown page(s) rendered, ${docs.length} document(s) indexed`);
for (const d of docs) console.log(`  ${d.kind === 'md' ? 'md  ' : 'html'}  ${d.url}`);
